global:
  scrape_interval: 1m
scrape_configs:
  - job_name: registry
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 15s
    static_configs:
      - targets:
        - registry:8888
