{{- if .Values.pod.disruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "registry.fullname" . }}
  namespace: {{ include "registry.namespace" . }}
  labels:
    {{- include "registry.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
       {{- include "registry.selectorLabels" . | nindent 6 }}
  {{- if not (or (hasKey .Values.pod.disruptionBudget "minAvailable") (hasKey .Values.pod.disruptionBudget "maxUnavailable")) }}
  minAvailable: 1 # Default value because minAvailable and maxUnavailable are not set
  {{- end }}
  {{- if hasKey .Values.pod.disruptionBudget "minAvailable" }}
  minAvailable: {{ .Values.pod.disruptionBudget.minAvailable }}
  {{- end }}
  {{- if hasKey .Values.pod.disruptionBudget "maxUnavailable" }}
  maxUnavailable: {{ .Values.pod.disruptionBudget.maxUnavailable }}
  {{- end }}
{{- end }}
